export * as algebra from "./core/algebra"
export {
  and,
  or,
  not,
  implies,
  oneOf,
  atLeast,
  atMost,
  exactly,
  through,
  term,
  relation,
  eq,
  ref,
  forAll,
  select,
  distinct,
  letRule,
  annotateRule,
  buildEvaluationProofDetails,
  getRuleAnnotations,
  sortRulesByPriorityAndKind,
  getTermInfo,
  withExclusions,
  evaluator,
  derives,
  given,
} from "./core/algebra"
export {
  createInMemoryAdapter,
  validateStratifiedNegation,
} from "./core/algebra-inmemory"
export {
  createPostgresAdapter,
  planPostgresPredicate,
  planPostgresRule,
} from "./core/algebra-postgres"
export type {
  Environment,
  FilterOptions,
  EvaluationProofDetails,
  EvaluationProof,
  EvaluatorAdapter,
  EvaluatorInstance,
  OutcomeToken,
  Relation,
  RuleAnnotations,
  RuleBranchOutcome,
  RuleReferenceToken,
  Rule,
  Term,
  TermInfo,
  UnaryPredicate,
} from "./core/algebra"
export type {
  InMemoryAdapterOptions,
  InMemoryRelationFacts,
} from "./core/algebra-inmemory"
export type {
  PlannedPostgresRule,
  PlannedPostgresPredicate,
  PostgresAdapterOptions,
  PostgresEdgeRelationSource,
  PostgresJoinTableRelationSource,
  PostgresProofDiagnostic,
  PostgresQueryExecutor,
  PostgresQueryResult,
  PostgresRelationMapping,
  PostgresRelationSource,
  PostgresTermEncoder,
  PostgresTermEncoding,
  PostgresTermDomainSource,
  PostgresTermSqlBinding,
} from "./core/algebra-postgres"
